# Generated by Django 3.1.3 on 2020-11-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ordem_de_venda',
            fields=[
                ('id_ordem_de_venda', models.IntegerField(primary_key=True, serialize=False)),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=40)),
            ],
        ),
    ]
