# Generated by Django 3.1.3 on 2020-12-08 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0001_initial'),
        ('controle_estoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ordem_de_venda',
            fields=[
                ('id_ordem_de_venda', models.AutoField(primary_key=True, serialize=False)),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=40)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pessoas.cliente')),
                ('id_lote_medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle_estoque.lote_medicamento')),
            ],
        ),
    ]
