# Generated by Django 3.1.3 on 2020-12-09 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
        ('cadastro_medicamentos', '0001_initial'),
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem_de_venda',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ordem_de_venda',
            name='data_de_venda',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ordem_de_venda',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordem_de_venda',
            name='venda',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ordem_de_venda',
            name='desconto',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ordem_de_compra',
            fields=[
                ('id_ordem_de_compra', models.AutoField(primary_key=True, serialize=False)),
                ('preco_lote', models.DecimalField(decimal_places=2, max_digits=40)),
                ('quantidade_lote', models.IntegerField(default=0)),
                ('data_de_compra', models.DateTimeField(auto_now=True)),
                ('id_fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pessoas.fornecedor')),
                ('id_medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro_medicamentos.medicamento')),
            ],
        ),
    ]
