# Generated by Django 3.1.3 on 2020-11-06 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controle_estoque', '0001_initial'),
        ('pessoas', '0001_initial'),
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem_de_venda',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pessoas.cliente'),
        ),
        migrations.AddField(
            model_name='ordem_de_venda',
            name='id_lote_medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle_estoque.lote_medicamento'),
        ),
    ]
