# Generated by Django 3.1.3 on 2020-12-09 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controle_estoque', '0001_initial'),
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordem_de_venda',
            name='id_lote_medicamento',
        ),
        migrations.CreateModel(
            name='venda_relacao_medicamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_lote_medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle_estoque.lote_medicamento')),
                ('id_ordem_de_venda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.ordem_de_venda')),
            ],
        ),
    ]
