# Generated by Django 3.1.3 on 2020-12-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_auto_20201209_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem_de_compra',
            name='data_de_compra',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ordem_de_venda',
            name='data_de_venda',
            field=models.DateField(null=True),
        ),
    ]
