# Generated by Django 3.1.3 on 2020-11-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_auto_20201106_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem_de_venda',
            name='id_ordem_de_venda',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
