# Generated by Django 3.1.3 on 2020-12-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_auto_20201209_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem_de_venda',
            name='percentual_desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=40),
        ),
    ]
