# Generated by Django 3.1.3 on 2020-12-08 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='medicamento',
            fields=[
                ('id_medicamento', models.AutoField(primary_key=True, serialize=False)),
                ('nome_medicamento', models.CharField(max_length=100)),
                ('classificacao', models.CharField(default='Sem tarja', max_length=100)),
                ('principio_ativo', models.CharField(max_length=100)),
                ('excluido', models.BooleanField(default=False)),
            ],
        ),
    ]
