# Generated by Django 3.1.3 on 2020-11-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_medicamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='classificacao',
            field=models.CharField(default='Sem tarja', max_length=100),
        ),
    ]
