# Generated by Django 3.1.3 on 2020-12-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_medicamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='principio_ativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_principio_ativo', models.CharField(max_length=100)),
            ],
        ),
    ]
