# Generated by Django 3.1.3 on 2020-11-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_medicamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='id_medicamento',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
