# Generated by Django 3.1.3 on 2021-05-12 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_medicamentos', '0002_principio_ativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='principio_ativo',
        ),
        migrations.AddField(
            model_name='medicamento',
            name='principio_ativo',
            field=models.ManyToManyField(to='cadastro_medicamentos.principio_ativo'),
        ),
    ]
