# Generated by Django 3.1.3 on 2021-05-22 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_medicamentos', '0003_auto_20210512_0259'),
    ]

    operations = [
        migrations.DeleteModel(
            name='principio_ativo',
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='nome_medicamento',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
