# Generated by Django 3.1.3 on 2021-05-22 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_medicamentos', '0004_auto_20210521_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='nome_medicamento',
            field=models.CharField(max_length=100),
        ),
    ]
