# Generated by Django 3.1.3 on 2021-05-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_medicamentos', '0008_auto_20210523_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principio_ativo2',
            name='nome_principio_ativo2',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
