# Generated by Django 3.1.3 on 2020-11-06 13:30

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=11)),
                ('telefone', models.CharField(max_length=12)),
                ('nome_cliente', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='fornecedor',
            fields=[
                ('id_fornecedor', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_fornecedor', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=14)),
                ('telefone', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='funcionario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('nome_funcionario', models.CharField(max_length=300)),
                ('cpf', models.CharField(max_length=11)),
                ('telefone', models.CharField(max_length=12)),
                ('cargo', models.CharField(max_length=100)),
                ('privilegio', models.CharField(max_length=100)),
                ('data_de_admissao', models.DateTimeField(auto_now_add=True)),
                ('data_de_demissao', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
