# Generated by Django 3.1.3 on 2020-12-09 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='funcionario',
            table='funcionarios',
        ),
    ]
