# Generated by Django 3.1.3 on 2020-12-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id_cliente',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='id_fornecedor',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
