# Generated by Django 3.1.3 on 2020-12-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='data_de_admissao',
            field=models.DateTimeField(),
        ),
    ]
