# Generated by Django 3.1.3 on 2020-11-29 01:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_auto_20201128_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='data_nascimento',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
