# Generated by Django 3.1.3 on 2020-12-08 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_auto_20201128_0641'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='clientes',
        ),
    ]
