# Generated by Django 3.1.3 on 2020-12-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0003_cliente_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='data_de_demissao',
            field=models.DateTimeField(default=None),
        ),
    ]
