# Generated by Django 3.1.3 on 2020-12-08 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0003_auto_20201208_0334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={},
        ),
        migrations.AlterModelTable(
            name='funcionario',
            table='funcionarios',
        ),
    ]
