# Generated by Django 3.1.3 on 2020-12-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0004_auto_20201207_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='data_de_demissao',
            field=models.DateTimeField(null=True),
        ),
    ]
