# Generated by Django 3.1 on 2020-12-09 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0004_cliente_ativo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='clientes',
        ),
    ]
