# Generated by Django 3.1.3 on 2020-12-07 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pessoas', '0005_auto_20201207_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={},
        ),
        migrations.AlterModelManagers(
            name='funcionario',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='id',
            field=models.AutoField(auto_created=True, default=1213, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='user',
            field=models.OneToOneField(default=12, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
