# Generated by Django 3.1.3 on 2020-11-06 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro_medicamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lote_medicamento',
            fields=[
                ('id_lote_medicamento', models.IntegerField(primary_key=True, serialize=False)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=40)),
                ('preco_com_desconto', models.DecimalField(decimal_places=2, max_digits=40)),
                ('quantidade', models.IntegerField()),
                ('quantidade_por_caixa', models.IntegerField()),
                ('concentracao', models.CharField(max_length=100)),
                ('formato', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('industria_farmaceutica', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('excluido', models.BooleanField(default=False)),
                ('id_medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro_medicamentos.medicamento')),
            ],
        ),
    ]
