# Generated by Django 3.1.3 on 2020-11-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote_medicamento',
            name='id_lote_medicamento',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
