# Generated by Django 3.1.3 on 2020-12-09 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lote_medicamento',
            table='lote_medicamento',
        ),
    ]
