# Generated by Django 3.1.3 on 2020-12-09 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_estoque', '0002_auto_20201209_0720'),
        ('controle_estoque', '0002_auto_20201209_1153'),
    ]

    operations = [
    ]
